# fly.toml app configuration file generated for dark-cherry-2684 on 2023-08-12T11:38:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-cherry-2684"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
